Story 1 into Main - Application Architecture
iO-Academy/2021-may-koalaCars pull request #5
Opened 2021-07-12 14:25 UTC by SniffleSneeze

- Wireframe 
- Data structure

2021-07-12 14:50 UTC, mporam requested changes
remove the big gap on the car details page

2021-07-12 14:50 UTC, mporam commented on css/normalize.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
why? remove this

2021-07-12 14:50 UTC, mporam commented on index.php
> +<?php
please remove this file

2021-07-12 14:50 UTC, mporam commented on details.php
> +<?php
remove this file

2021-07-12 14:50 UTC, mporam commented on utilities/requestJson.php
> +<?php
remove this file

2021-07-12 15:05 UTC, nealioa submitted a review, later dismissed

2021-07-15 08:34 UTC, mporam approved these changes

2021-07-15 08:35 UTC, merged